import { StyleSheet, Text, View } from 'react-native'
const styles = StyleSheet.create({
    container:{
        backgroundColor:'black',
        flex: 1,
        padding: 6,
      },
      header:{
        justifyContent:'space-between',
        flexDirection:'row',
        paddingBottom:20,
        paddingRight:110,
        marginVertical:10
      },
      title:{
        color:'#BF5700',
        fontSize:30,
        fontWeight:'bold',
        marginHorizontal:1,
        marginVertical:-3
    },
    coverImage:{
        width:300,
        height:300,
        marginLeft:40,
        borderRadius:10,
        borderColor:'#BF5700',
        borderWidth:2
    },
    text:{
        fontSize:30,
        fontFamily:"serif",
        color:'#BF5700'
    },
    artist:{
        fontSize:20,
        color:'#DDDBCB'
    },
    content:{
        alignItems:'center',
        justifyContent:'center',
        flexDirection:'column',
        marginTop:10
    },
    heartContainer:{
       marginLeft:350,
       marginTop:10
    },
    controller:{
        flexDirection:'row',
        alignItems:'center',
        justifyContent:'space-between',
        paddingHorizontal:10,
        marginTop:20,
        marginLeft:5
    },
    repeat:{
        marginLeft:230
    },
    playerControlContainer:{
        flexDirection:'row',
        justifyContent:'space-between',
        alignItems:'center',
        gap:20,
        paddingHorizontal:60,
        marginTop:30
      }
})
export default styles

